#!/bin/bash

# Environment variables:
# - NO_CBUILD: When the value is `1`, it doesn't use cbuild tool and use bazel directly.

set -ex
DIR_OF_THIS_FILE=$(cd $(dirname $0); pwd)
PROJECT_ROOT=$DIR_OF_THIS_FILE/../..
cd $PROJECT_ROOT

if [[ "$NO_CBUILD" == "1" ]]; then
    COMMAND="bazel"
else
    COMMAND="builders/tools/bazel-debian"
fi

builders/tools/bazel-debian build //tools/azure_encryption:azure_encryption_test --config=azure_azure --//:build_flavor=non_prod
gdb ./bazel-bin/tools/azure_encryption/azure_encryption_test
